version: '3.8'
services:
  xwiki-mysql:
    image: mysql:5.7
    container_name: xwiki-mysql
    networks:
      xwiki-network:
        aliases:
          - mysql  
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql-config:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: xwiki
      MYSQL_USER: xwiki
      MYSQL_PASSWORD: xwiki
      MYSQL_DATABASE: xwiki
      character-set-server: utf8
      collation-server: utf8_bin
      explicit-defaults-for-timestamp: '1'

  xwiki:
    # build:
    #   context: .
    #   dockerfile: dockerfile_xwiki
    image: xwiki:lts-mysql-tomcat
    container_name: xwiki
    depends_on:
      - xwiki-mysql
    networks:
      xwiki-network:
        aliases:
          - xwiki      
    ports:
      - "8080:8080"
    extra_hosts:
      - "xwiki.mv: 192.168.56.101"      
    volumes:
      - ./xwiki_data:/usr/local/xwiki
    environment:
      DB_USER: xwiki
      DB_PASSWORD: xwiki
      DB_DATABASE: xwiki
      DB_HOST: xwiki-mysql

  xwiki-cas:    
    image: apereo/cas:v5.0.6
    container_name: xwiki-cas
    depends_on:
      - xwiki-mysql
    extra_hosts:
      - "xwiki.mv: 192.168.56.101"      
    networks:
      xwiki-network:
        aliases:
          - cas
    ports:
      - ${CAS_HTTP_PORT:-9080}:8080
      - ${CAS_HTTPS_PORT:-9443}:8443
    volumes:
    -  ./cas-config/config/:/cas-overlay/etc/cas/config/
    -  ./cas-config/resources/application.properties:/cas-overlay/src/main/resources/application.properties

  xwiki-httpd:
    build:
      context: ./build-httpd
    container_name: xwiki-httpd
    ports:
      - 443:443
      - 80:80
    volumes:
      - xwiki_httpd_conf:/usr/local/apache2/conf
      - xwiki_httpd_log:/usr/local/apache2/logs
    extra_hosts:
      - "xwiki.mv: 192.168.56.101"
    networks:
      xwiki-network:
        aliases:
          - httpd

networks:
  xwiki-network:
    driver: bridge

volumes:
  xwiki_httpd_conf:
  xwiki_httpd_log:

