# Usar una imagen base de Java 17
FROM openjdk:17-bullseye

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Instalar Maven y Git
RUN apt-get update && \
    apt-get install -y maven git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Configurar el entorno de Java y Maven
ENV JAVA_HOME /usr/local/openjdk-17
ENV MAVEN_HOME /usr/share/maven

# Opcional: copiar el código fuente de tu proyecto al contenedor
COPY ./java-cas-client-4.0.3 /app

# Opcional: construir el proyecto automáticamente al construir la imagen
RUN mvn package

# Comando para ejecutar cuando se inicie el contenedor
CMD ["bash"]
