version: '3.8'
services:
  xwiki-postgres:
    image: "postgres:16"
    container_name: xwiki-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_ROOT_PASSWORD=xwiki
      - POSTGRES_PASSWORD=xwiki
      - POSTGRES_USER=xwiki
      - POSTGRES_DB=xwiki
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    networks:
      xwiki-network:
        aliases:
          - postgres

  xwiki:
    image: xwiki:stable-postgres-tomcat
    container_name: xwiki
    depends_on:
      - xwiki-postgres
    networks:
      xwiki-network:
        aliases:
          - xwiki      
    ports:
      - "8080:8080"
    extra_hosts:   
      - "cas: 192.168.56.101"      
    
    volumes:
      - xwiki_data:/usr/local/xwiki
      - ./xwiki-config/xwiki.cfg:/usr/local/xwiki/data/xwiki.cfg     
      - ./xwiki-config/xwiki.properties:/usr/local/xwiki/data/xwiki.properties       
      - ./xwiki-config/cacerts:/opt/java/openjdk/lib/security/cacerts   
 
    environment:
      DB_USER: xwiki
      DB_PASSWORD: xwiki
      DB_DATABASE: xwiki
      DB_HOST: xwiki-postgres

  xwiki-cas:    
    image: apereo/cas:v5.0.6
    container_name: xwiki-cas         
    networks:
      xwiki-network:
        aliases:
          - cas
    ports:
      - ${CAS_HTTP_PORT:-9080}:8080
      - ${CAS_HTTPS_PORT:-9443}:8443
    volumes:
    - ./cas-config/config:/cas-overlay/etc/cas/config
    - ./cas-config/application.properties:/cas-overlay/src/main/resources/application.properties
    - ./cas-config/thekeystore:/etc/cas/thekeystore
    - ./cas-config/xwiki-10001000.json:/cas-overlay/src/main/resources/services/xwiki-10001000.json

  xwiki-httpd:
    build:
      context: ./build-httpd
    container_name: xwiki-httpd
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./build-httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - httpd_conf:/usr/local/apache2/conf
      - httpd_log:/usr/local/apache2/logs

    networks:
      xwiki-network:
        aliases:
          - httpd

networks:
  xwiki-network:
    driver: bridge

volumes:
  xwiki_data:
  postgres_data:
  httpd_conf:
  httpd_log:
  

