version: '3.8'
services:

  xwiki:
    image: ${DOCKER_REPOSITORY}/xwiki:${XWIKI_VER}    
    container_name: xwiki
    restart: always  
    networks:
      xwiki-network:
        aliases:
          - xwiki      
    volumes:
      - ${XWIKI_DATA}:/usr/local/xwiki
      - ./xwiki-config/xwiki.cfg.${ENTORNO}:/usr/local/xwiki/data/xwiki.cfg     
      - ./xwiki-config/xwiki.properties.${ENTORNO}:/usr/local/xwiki/data/xwiki.properties       
      - ./xwiki-config/cacerts.${ENTORNO}:/opt/java/openjdk/lib/security/cacerts   
      - ./xwiki-config/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    environment:
      - DB_USER=${XWIKI_DB_USER}
      - DB_PASSWORD=${XWIKI_DB_PASS}
      - DB_DATABASE=${XWIKI_DB_DATABASE}
      - DB_HOST=${XWIKI_DB_HOST}
      - DB_PORT=${XWIKI_DB_PORT}
      - CONTEXT_PATH=aplicaciones#ciberwiki

  xwiki-httpd:
    image: ${DOCKER_REPOSITORY}/httpd-ciberwiki:${HTTPD_VER}
    container_name: xwiki-httpd
    restart: always  
    ports:
      - 443:443
      - 80:80    
    volumes:
      - ./build-httpd/httpd.conf.${ENTORNO}:/usr/local/apache2/conf/httpd.conf
      - ./build-httpd/${CERT_CRT}:/usr/local/apache2/conf/cert.crt
      - ./build-httpd/${CERT_KEY}:/usr/local/apache2/conf/cert.key
    networks:
      xwiki-network:
        aliases:
          - httpd


networks:
  xwiki-network:
    driver: bridge

