version: '3.8'
services:
  mysql-xwiki:
    image: mysql:5.7
    container_name: mysql-xwiki
    networks:
      - xwiki-nw
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: xwiki
      MYSQL_USER: xwiki
      MYSQL_PASSWORD: xwiki
      MYSQL_DATABASE: xwiki
      character-set-server: utf8
      collation-server: utf8_bin
      explicit-defaults-for-timestamp: '1'

  xwiki:
    image: xwiki:lts-mysql-tomcat
    container_name: xwiki
    depends_on:
      - mysql-xwiki
    networks:
      - xwiki-nw
    ports:
      - "8080:8080"
    volumes:
      - ./data_xwiki:/usr/local/xwiki
    environment:
      DB_USER: xwiki
      DB_PASSWORD: xwiki
      DB_DATABASE: xwiki
      DB_HOST: mysql-xwiki

  apereo:
    image: apereo/cas:6.6.11
    container_name: apereo
    depends_on:
      - mysql-xwiki
    networks:
      - xwiki-nw
    ports:
      - "18080:8080"
      - "18443:8443"
    # volumes:
    #   - ./cas/config:/etc/cas/config
    # environment:
    #   - CAS_SERVER_NAME=https://xwiki.mv
    #   - CAS_SERVER_PREFIX=https://xwiki.mv/cas


networks:
  xwiki-nw:
    driver: bridge
